title: Project work Mete.io software
description: DTM Software Engineering project work for the development of the software Mete.io
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
